<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.S3" Version="4.0.18.6" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageVersion Include="Azure.Storage.Blobs.Batch" Version="12.24.0" />
    <PackageVersion Include="Google.Cloud.Storage.V1" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="6.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="MinVer" Version="6.0.0" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="Ramstack.Globbing" Version="2.3.3" />
    <PackageVersion Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>
</Project>
