name: Test AmazonS3FileSystem

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    name: Runs on ubuntu-latest using LocalStack
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566 # LocalStack edge port
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Debug

      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Amazon
