name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:

  main:
    name: "Test: Main projects, ${{ matrix.os.name }}"
    runs-on: ${{ matrix.os.id }}
    strategy:
      matrix:
        os:
          - id: windows-latest
            name: Windows
          - id: ubuntu-latest
            name: Ubuntu
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter "TestCategory!~Cloud"

  azure:
    name: "Test: AzureFileSystem, Azurite"
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Azure

  s3:
    name: "Test: S3FileSystem, Minio"
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Amazon
