name: Test AmazonS3FileSystem

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    name: Runs on ubuntu-latest using LocalStack
    runs-on: ubuntu-latest

    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        options: >
          --entrypoint "/usr/bin/minio" --command "server /data"

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Debug

      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Amazon
