name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:

  main:
    name: "Test: Main projects, ${{ matrix.os.name }}"
    runs-on: ${{ matrix.os.id }}
    strategy:
      matrix:
        os:
          - id: windows-latest
            name: Windows
          - id: ubuntu-latest
            name: Ubuntu
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
            10.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter "TestCategory!~Cloud"

  azure:
    name: "Test: AzureFileSystem"
    runs-on: ubuntu-latest
    steps:
      - name: Start Azurite
        run: |
          docker run -d \
            -p 10000:10000 \
            -p 10001:10001 \
            -p 10002:10002 \
            mcr.microsoft.com/azure-storage/azurite \
            azurite --skipApiVersionCheck \
                    --blobHost 0.0.0.0 \
                    --queueHost 0.0.0.0 \
                    --tableHost 0.0.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
            10.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Azure -maxcpucount:1

  s3:
    name: "Test: S3FileSystem"
    runs-on: ubuntu-latest
    services:
      rustfs:
        image: docker.io/rustfs/rustfs:latest
        ports:
          - 9000:9000
          - 9001:9001
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
            10.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud:Amazon
