name: Test Azure-based project

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    name: Runs on ubuntu-latest using Azurite
    runs-on: ubuntu-latest

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Debug

      - name: Test
        run: dotnet test --no-build --filter TestCategory=Cloud
